{
 "title": "nyc taxi data dashboard",
 "time": { "from": "2024-02-26T21:58:13.182Z", "to": "2024-04-01T10:57:14.166Z" },
 "panels": [
  {
   "title": "prediction drift",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", prediction_drift FROM monitoring_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "number of drifted columns",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", num_drifted_columns FROM monitoring_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "missing values share",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", share_missing_values FROM monitoring_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "fare_amount quantile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", fare_amount_quantile FROM monitoring_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "correlation between prediction and trip_distance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", prediction_trip_distance_corr FROM monitoring_metrics LIMIT 50 "
    }
   ]
  }
 ]
}